import type { PlatformConfig, PlatformId, ClosingFeeTier } from '@/types'

/** Amazon India price-based closing fee tiers (shared across all categories) */
const amazonInClosingFees: ClosingFeeTier[] = [
  { maxPrice: 250, fee: 9 },
  { maxPrice: 500, fee: 12 },
  { fee: 20 },           // above ₹500
]

export const PLATFORMS: Record<PlatformId, PlatformConfig> = {
  'amazon-in': {
    id: 'amazon-in',
    name: 'Amazon India',
    shortName: 'Amazon.in',
    currency: 'INR',
    flag: '🇮🇳',
    color: '#FF9900',
    bgColor: '#FF990015',
    hasGST: true,
    hasTCS: true,
    hasCOD: true,
    paymentRate: 0.0,
    paymentFixed: 0,
    gstRate: 0.18,
    tcsRate: 0.01,
    codRate: 0.02,
    shippingFeeDefault: 75,
    description: 'India\'s largest marketplace. Now features 0% commission on select items <₹1000',
    lastUpdated: '2026-03-16',
    feeSource: 'https://sell.amazon.in/fees-and-pricing',
    categories: [
      { name: 'Apparel & Clothing',      commissionRate: 0.07, fixedFee: 20, minFee: 1, closingFeeTiers: amazonInClosingFees },
      { name: 'Mobile Phones',           commissionRate: 0.05, fixedFee: 20, minFee: 1, closingFeeTiers: amazonInClosingFees },
      { name: 'Laptops & Tablets',       commissionRate: 0.06, fixedFee: 20, minFee: 1, closingFeeTiers: amazonInClosingFees },
      { name: 'Consumer Electronics',    commissionRate: 0.07, fixedFee: 20, minFee: 1, closingFeeTiers: amazonInClosingFees },
      { name: 'Books',                   commissionRate: 0.08, fixedFee: 9,  minFee: 1, closingFeeTiers: amazonInClosingFees },
      { name: 'Home Decor',              commissionRate: 0.10, fixedFee: 20, minFee: 1, closingFeeTiers: amazonInClosingFees },
      { name: 'Home & Kitchen',          commissionRate: 0.09, fixedFee: 20, minFee: 1, closingFeeTiers: amazonInClosingFees },
      { name: 'Jewelry',                 commissionRate: 0.20, fixedFee: 20, minFee: 5, closingFeeTiers: amazonInClosingFees },
      { name: 'Shoes & Footwear',        commissionRate: 0.10, fixedFee: 20, minFee: 1, closingFeeTiers: amazonInClosingFees },
      { name: 'Sports & Outdoors',       commissionRate: 0.09, fixedFee: 20, minFee: 1, closingFeeTiers: amazonInClosingFees },
      { name: 'Toys & Games',            commissionRate: 0.09, fixedFee: 20, minFee: 1, closingFeeTiers: amazonInClosingFees },
      { name: 'Beauty & Personal Care',  commissionRate: 0.10, fixedFee: 20, minFee: 1, closingFeeTiers: amazonInClosingFees },
      { name: 'Health & Household',      commissionRate: 0.08, fixedFee: 20, minFee: 1, closingFeeTiers: amazonInClosingFees },
      { name: 'Grocery & Gourmet',       commissionRate: 0.05, fixedFee: 9,  minFee: 1, closingFeeTiers: amazonInClosingFees },
      { name: 'Automotive Accessories',  commissionRate: 0.10, fixedFee: 20, minFee: 1, closingFeeTiers: amazonInClosingFees },
    ],
  },

  'amazon-us': {
    id: 'amazon-us',
    name: 'Amazon USA',
    shortName: 'Amazon.com',
    currency: 'USD',
    flag: '🇺🇸',
    color: '#FF9900',
    bgColor: '#FF990015',
    hasGST: false,
    hasTCS: false,
    hasCOD: false,
    paymentRate: 0.029,
    paymentFixed: 0.30,
    gstRate: 0,
    tcsRate: 0,
    codRate: 0,
    shippingFeeDefault: 5,
    description: 'World\'s largest marketplace with tiered referral fees',
    categories: [
      {
        name: 'Apparel & Accessories',
        commissionRate: 0.17,
        fixedFee: 0,
        minFee: 0.30,
        tiers: [
          { max: 15, rate: 0.05 },
          { max: 20, rate: 0.10 },
          { max: Infinity, rate: 0.17 },
        ],
      },
      { name: 'Books', commissionRate: 0.15, fixedFee: 1.80, minFee: 0.30 },
      { name: 'Consumer Electronics', commissionRate: 0.08, fixedFee: 0, minFee: 0.30 },
      { name: 'Device Accessories', commissionRate: 0.45, fixedFee: 0, minFee: 0.30 },
      { name: 'Home & Garden', commissionRate: 0.15, fixedFee: 0, minFee: 0.30 },
      { name: 'Jewelry', commissionRate: 0.20, fixedFee: 0, minFee: 0.30 },
      { name: 'Shoes & Handbags', commissionRate: 0.15, fixedFee: 0, minFee: 0.30 },
      { name: 'Sports & Outdoors', commissionRate: 0.15, fixedFee: 0, minFee: 0.30 },
      { name: 'Toys & Games', commissionRate: 0.15, fixedFee: 0, minFee: 0.30 },
      { name: 'Beauty & Personal Care', commissionRate: 0.08, fixedFee: 0, minFee: 0.30 },
      { name: 'Health & Household', commissionRate: 0.15, fixedFee: 0, minFee: 0.30 },
      { name: 'Baby Products', commissionRate: 0.08, fixedFee: 0, minFee: 0.30 },
      { name: 'Office Products', commissionRate: 0.15, fixedFee: 0, minFee: 0.30 },
      { name: 'Pet Supplies', commissionRate: 0.15, fixedFee: 0, minFee: 0.30 },
    ],
  },

  flipkart: {
    id: 'flipkart',
    name: 'Flipkart',
    shortName: 'Flipkart',
    currency: 'INR',
    flag: '🇮🇳',
    color: '#2874F0',
    bgColor: '#2874F015',
    hasGST: true,
    hasTCS: true,
    hasCOD: true,
    paymentRate: 0.02,
    paymentFixed: 0,
    gstRate: 0.18,
    tcsRate: 0.01,
    codRate: 0.02,
    shippingFeeDefault: 75,
    description: 'India\'s top fashion & electronics marketplace',
    lastUpdated: '2025-11-01',
    feeSource: 'https://seller.flipkart.com/fees-and-commission',
    categories: [
      { name: 'Apparel / Fashion',                      commissionRate: 0.07, fixedFee: 57, minFee: 1 },
      { name: 'Books & Media',                          commissionRate: 0.10, fixedFee: 30, minFee: 1 },
      { name: 'Consumer Electronics (Laptops/Tablets)', commissionRate: 0.05, fixedFee: 57, minFee: 1 },
      { name: 'Electronics Accessories',                commissionRate: 0.09, fixedFee: 57, minFee: 1 },
      { name: 'Home & Furniture',                       commissionRate: 0.12, fixedFee: 57, minFee: 1 },
      { name: 'Mobile Phones',                          commissionRate: 0.04, fixedFee: 57, minFee: 1 },
      { name: 'Footwear',                               commissionRate: 0.10, fixedFee: 57, minFee: 1 },
      { name: 'Toys & Baby Products',                   commissionRate: 0.12, fixedFee: 30, minFee: 1 },
      { name: 'Beauty & Wellness',                      commissionRate: 0.10, fixedFee: 30, minFee: 1 },
      { name: 'Jewelry & Accessories',                  commissionRate: 0.15, fixedFee: 57, minFee: 5 },
      { name: 'Sports & Fitness',                       commissionRate: 0.12, fixedFee: 57, minFee: 1 },
      { name: 'Food & Nutrition',                       commissionRate: 0.10, fixedFee: 30, minFee: 1 },
    ],
  },

  meesho: {
    id: 'meesho',
    name: 'Meesho',
    shortName: 'Meesho',
    currency: 'INR',
    flag: '🇮🇳',
    color: '#9F2089',
    bgColor: '#9F208915',
    hasGST: true,
    hasTCS: true,
    hasCOD: true,
    paymentRate: 0,
    paymentFixed: 0,
    gstRate: 0.18,
    tcsRate: 0.01,
    codRate: 0,
    shippingFeeDefault: 60,
    description: '0% commission marketplace — only pay for shipping',
    categories: [
      { name: 'Apparel & Clothing',      commissionRate: 0.00, fixedFee: 0, minFee: 0 },
      { name: 'Home & Kitchen',          commissionRate: 0.00, fixedFee: 0, minFee: 0 },
      { name: 'Beauty & Personal Care',  commissionRate: 0.00, fixedFee: 0, minFee: 0 },
      { name: 'Footwear',                commissionRate: 0.00, fixedFee: 0, minFee: 0 },
      { name: 'Jewelry & Accessories',   commissionRate: 0.00, fixedFee: 0, minFee: 0 },
      { name: 'Electronics',             commissionRate: 0.00, fixedFee: 0, minFee: 0 },
      { name: 'Mobile Phones',           commissionRate: 0.00, fixedFee: 0, minFee: 0 },
      { name: 'Bags & Luggage',          commissionRate: 0.00, fixedFee: 0, minFee: 0 },
      { name: 'Toys & Baby Products',    commissionRate: 0.00, fixedFee: 0, minFee: 0 },
      { name: 'Sports & Fitness',        commissionRate: 0.00, fixedFee: 0, minFee: 0 },
    ],
  },

  ebay: {
    id: 'ebay',
    name: 'eBay',
    shortName: 'eBay',
    currency: 'USD',
    flag: '🇺🇸',
    color: '#E53238',
    bgColor: '#E5323815',
    hasGST: false,
    hasTCS: false,
    hasCOD: false,
    paymentRate: 0,
    paymentFixed: 0,
    gstRate: 0,
    tcsRate: 0,
    codRate: 0,
    shippingFeeDefault: 0,
    description: 'Global C2C & B2C marketplace with final value fees (includes payment processing)',
    lastUpdated: '2025-02-14',
    feeSource: 'https://www.ebay.com/sellercenter/resources/seller-updates/2025-january/final-value-fee',
    categories: [
      { name: 'Consumer Electronics',   commissionRate: 0.1325, fixedFee: 0.30, minFee: 0 },
      { name: 'Clothing & Accessories', commissionRate: 0.1325, fixedFee: 0.30, minFee: 0 },
      { name: 'Collectibles & Art',     commissionRate: 0.1325, fixedFee: 0.30, minFee: 0 },
      { name: 'Books, Movies & Music',  commissionRate: 0.1465, fixedFee: 0.30, minFee: 0 },
      { name: 'Home & Garden',          commissionRate: 0.1325, fixedFee: 0.30, minFee: 0 },
      { name: 'Motors Parts & Accessories', commissionRate: 0.129, fixedFee: 0.30, minFee: 0 },
      { name: 'Sporting Goods',         commissionRate: 0.1325, fixedFee: 0.30, minFee: 0 },
      { name: 'Toys & Hobbies',         commissionRate: 0.1325, fixedFee: 0.30, minFee: 0 },
      { name: 'Health & Beauty',        commissionRate: 0.1325, fixedFee: 0.30, minFee: 0 },
      { name: 'Baby',                   commissionRate: 0.1325, fixedFee: 0.30, minFee: 0 },
      { name: 'Jewelry & Watches',      commissionRate: 0.15,   fixedFee: 0.30, minFee: 0 },
    ],
  },

  walmart: {
    id: 'walmart',
    name: 'Walmart',
    shortName: 'Walmart',
    currency: 'USD',
    flag: '🇺🇸',
    color: '#0071CE',
    bgColor: '#0071CE15',
    hasGST: false,
    hasTCS: false,
    hasCOD: false,
    paymentRate: 0.029,
    paymentFixed: 0,
    gstRate: 0,
    tcsRate: 0,
    codRate: 0,
    shippingFeeDefault: 0,
    description: 'USA\'s retail giant with competitive referral fees',
    lastUpdated: '2025-01-01',
    feeSource: 'https://sellerhelp.walmart.com/s/guide?article=000009164',
    categories: [
      { name: 'Apparel (≤$15)',       commissionRate: 0.05, fixedFee: 0, minFee: 0 },
      { name: 'Apparel ($15–$20)',    commissionRate: 0.10, fixedFee: 0, minFee: 0 },
      { name: 'Apparel (>$20)',       commissionRate: 0.15, fixedFee: 0, minFee: 0 },
      { name: 'Consumer Electronics', commissionRate: 0.08, fixedFee: 0, minFee: 0 },
      { name: 'Health & Beauty',      commissionRate: 0.15, fixedFee: 0, minFee: 0 },
      { name: 'Home & Garden',        commissionRate: 0.15, fixedFee: 0, minFee: 0 },
      { name: 'Sporting Goods',       commissionRate: 0.15, fixedFee: 0, minFee: 0 },
      { name: 'Toys & Baby',          commissionRate: 0.15, fixedFee: 0, minFee: 0 },
      { name: 'Pet Supplies',         commissionRate: 0.15, fixedFee: 0, minFee: 0 },
      { name: 'Office Products',      commissionRate: 0.15, fixedFee: 0, minFee: 0 },
      { name: 'Books & Media',        commissionRate: 0.15, fixedFee: 0, minFee: 0 },
      { name: 'Grocery & Gourmet',    commissionRate: 0.08, fixedFee: 0, minFee: 0 },
      { name: 'Jewelry',              commissionRate: 0.20, fixedFee: 0, minFee: 0 },
    ],
  },

  shopee: {
    id: 'shopee',
    name: 'Shopee',
    shortName: 'Shopee',
    currency: 'SGD',
    flag: '🇸🇬',
    color: '#EE4D2D',
    bgColor: '#EE4D2D15',
    hasGST: false,
    hasTCS: false,
    hasCOD: false,
    paymentRate: 0.0218,
    paymentFixed: 0,
    gstRate: 0,
    tcsRate: 0,
    codRate: 0,
    shippingFeeDefault: 0,
    description: 'Leading Southeast Asian marketplace (Singapore)',
    lastUpdated: '2025-06-01',
    feeSource: 'https://seller.shopee.sg/edu/article/8236',
    categories: [
      { name: 'Consumer Electronics',  commissionRate: 0.03, fixedFee: 0, minFee: 0 },
      { name: 'Fashion & Clothing',    commissionRate: 0.06, fixedFee: 0, minFee: 0 },
      { name: 'Home & Living',         commissionRate: 0.04, fixedFee: 0, minFee: 0 },
      { name: 'Beauty & Personal Care',commissionRate: 0.05, fixedFee: 0, minFee: 0 },
      { name: 'Sports & Outdoors',     commissionRate: 0.04, fixedFee: 0, minFee: 0 },
      { name: 'Food & Groceries',      commissionRate: 0.03, fixedFee: 0, minFee: 0 },
      { name: 'Babies & Toys',         commissionRate: 0.04, fixedFee: 0, minFee: 0 },
      { name: 'Shoes & Bags',          commissionRate: 0.06, fixedFee: 0, minFee: 0 },
      { name: 'Watches & Jewelry',     commissionRate: 0.05, fixedFee: 0, minFee: 0 },
      { name: 'Automotive',            commissionRate: 0.03, fixedFee: 0, minFee: 0 },
    ],
  },

  lazada: {
    id: 'lazada',
    name: 'Lazada',
    shortName: 'Lazada',
    currency: 'SGD',
    flag: '🌏',
    color: '#0F1461',
    bgColor: '#0F146115',
    hasGST: false,
    hasTCS: false,
    hasCOD: false,
    paymentRate: 0.005,
    paymentFixed: 0,
    gstRate: 0,
    tcsRate: 0,
    codRate: 0,
    shippingFeeDefault: 0,
    description: 'Top SEA marketplace — Thailand, Malaysia, Philippines, Indonesia',
    lastUpdated: '2025-06-01',
    feeSource: 'https://sellercenter.lazada.sg/apps/seller/education/detail?articleId=3',
    categories: [
      { name: 'Consumer Electronics', commissionRate: 0.04, fixedFee: 0, minFee: 0 },
      { name: 'Fashion & Apparel',    commissionRate: 0.07, fixedFee: 0, minFee: 0 },
      { name: 'Home & Living',        commissionRate: 0.05, fixedFee: 0, minFee: 0 },
      { name: 'Beauty & Health',      commissionRate: 0.06, fixedFee: 0, minFee: 0 },
      { name: 'Sports & Fitness',     commissionRate: 0.05, fixedFee: 0, minFee: 0 },
      { name: 'Toys & Baby',          commissionRate: 0.06, fixedFee: 0, minFee: 0 },
      { name: 'Groceries',            commissionRate: 0.03, fixedFee: 0, minFee: 0 },
      { name: 'Automotive',           commissionRate: 0.04, fixedFee: 0, minFee: 0 },
      { name: 'Watches & Jewelry',    commissionRate: 0.08, fixedFee: 0, minFee: 0 },
    ],
  },
}

export const PLATFORM_LIST = Object.values(PLATFORMS)

export function getPlatform(id: string): PlatformConfig | undefined {
  return PLATFORMS[id as PlatformId]
}

export function getCategoriesForPlatform(platformId: PlatformId) {
  return PLATFORMS[platformId]?.categories ?? []
}

export function getDefaultCategory(platformId: PlatformId): string {
  const categories = getCategoriesForPlatform(platformId)
  return categories[0]?.name ?? ''
}
